name: Terraform CI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write
  security-events: write

jobs:
  validate:
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: annkur-sharma/AzureCode06-GitHubActions/.github/workflows/terraform-validate.yml@v3
    with:
      working_directory: INFRA01
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  plan:
    # needs: validate
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: annkur-sharma/AzureCode06-GitHubActions/.github/workflows/terraform-plan.yml@v2
    with:
      working_directory: INFRA01
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

  apply:
    # needs: plan
    if: github.ref == 'refs/heads/main'
    uses: annkur-sharma/AzureCode06-GitHubActions/.github/workflows/terraform-apply.yml@v2
    with:
      working_directory: INFRA01
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
