name: Terraform CI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write
  security-events: write

jobs:
  validate:
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: annkur-sharma/AzureCode06-GitHubActions/.github/workflows/terraform-validate.yml@v1
    with:
      working_directory: INFRA01
    secrets: inherit

  plan:
    needs: validate
    if: startsWith(github.ref, 'refs/heads/feature/')
    uses: annkur-sharma/AzureCode06-GitHubActions/.github/workflows/terraform-plan.yml@v1
    with:
      working_directory: INFRA01
    secrets: inherit

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    uses: annkur-sharma/AzureCode06-GitHubActions/.github/workflows/terraform-apply.yml@v1
    with:
      working_directory: INFRA01
    secrets: inherit
